In [1]:
import torch
from torch import nn

In [2]:
x = torch.empty(3,4)
print(x.shape)
print(x)

torch.Size([3, 4])
tensor([[-8.8075e-11,  4.3589e-41, -8.8075e-11,  4.3589e-41],
        [ 0.0000e+00,  0.0000e+00,  9.1485e-39,  0.0000e+00],
        [ 7.9433e+36,  4.3589e-41,  0.0000e+00,  0.0000e+00]])


In [3]:
zeros = torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
ones = torch.ones(2,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [7]:
torch.manual_seed(123)
random_tensor = torch.rand(2,4)
print(random_tensor)

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025]])


In [10]:
x = torch.ones(2,2,3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [11]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[-8.8075e-11,  4.3589e-41,  2.2686e-15],
         [ 0.0000e+00,  2.2653e-15,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  2.4513e-15,  0.0000e+00]]])


In [14]:
zeros_like_x = torch.rand_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0.1841, 0.7264, 0.3153],
         [0.6871, 0.0756, 0.1966]],

        [[0.3164, 0.4017, 0.1186],
         [0.8274, 0.3821, 0.6605]]])


In [20]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
zeros_like_x = zeros_like_x.to(device)
print(zeros_like_x.device)

cuda:0


In [23]:
a = torch.ones((2,3), dtype = torch.int16)
b = torch.rand((2,4,5), dtype = torch.float64) * 20

In [24]:
print(b)

tensor([[[16.5715,  1.8761,  3.9193,  4.4067,  3.8925],
         [ 8.2917, 14.8614,  6.5039, 12.3441,  3.6580],
         [ 5.0634, 12.7263, 13.6900,  7.5232, 11.2810],
         [ 8.3969, 18.8634,  9.6621, 10.5271,  4.7819]],

        [[12.6182,  4.4000,  8.1388,  1.3416,  2.0088],
         [10.2195,  3.3494, 13.2202, 12.7945, 15.2302],
         [17.1129, 15.7295, 16.0133, 11.2816,  4.0229],
         [18.6518,  5.0834,  8.5288, 18.1106,  4.1597]]], dtype=torch.float64)


In [25]:
c = b.to(torch.int32)
print(c)

tensor([[[16,  1,  3,  4,  3],
         [ 8, 14,  6, 12,  3],
         [ 5, 12, 13,  7, 11],
         [ 8, 18,  9, 10,  4]],

        [[12,  4,  8,  1,  2],
         [10,  3, 13, 12, 15],
         [17, 15, 16, 11,  4],
         [18,  5,  8, 18,  4]]], dtype=torch.int32)


In [28]:
ones = torch.ones((2,2))
twos = ones * 2
threes = (torch.ones((2,2)) * 7 - 1)/2
fours = twos ** 2
sqrt2s = (twos.to(torch.float64)**0.5)

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]], dtype=torch.float64)


In [29]:
powers2 = twos ** torch.tensor([[1,2],[3,4]])
fives = ones + fours
dozens = threes * fours

In [30]:
print(powers2)
print(fives)
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [34]:
rand = torch.rand(2, 4)
doubles  = rand + (torch.ones((1,4)) * 2)

print(rand)
print(doubles)

tensor([[0.9753, 0.2518, 0.7204, 0.6959],
        [0.6397, 0.8954, 0.2979, 0.6314]])
tensor([[2.9753, 2.2518, 2.7204, 2.6959],
        [2.6397, 2.8954, 2.2979, 2.6314]])


In [40]:
a = torch.rand((2,4, 3))

In [41]:
b = torch.rand((1, 3))
c = a * b
print(a)
print(b)
print(c)

tensor([[[0.1163, 0.4938, 0.5938],
         [0.1594, 0.2132, 0.0206],
         [0.3247, 0.9355, 0.5855],
         [0.4695, 0.5201, 0.8118]],

        [[0.0585, 0.1142, 0.3338],
         [0.2122, 0.7579, 0.8533],
         [0.0149, 0.0757, 0.0131],
         [0.6886, 0.9024, 0.1123]]])
tensor([[0.2685, 0.6591, 0.1735]])
tensor([[[0.0312, 0.3255, 0.1030],
         [0.0428, 0.1405, 0.0036],
         [0.0872, 0.6166, 0.1016],
         [0.1261, 0.3428, 0.1408]],

        [[0.0157, 0.0753, 0.0579],
         [0.0570, 0.4995, 0.1481],
         [0.0040, 0.0499, 0.0023],
         [0.1849, 0.5948, 0.0195]]])


Altering tensors in place

In [42]:
import math
a = torch.tensor([0, math.pi/4, math.pi/2, 3 * math.pi/4, math.pi])
print('a:')
print(a)
print(torch.sin(a))
print(a)

b = torch.tensor([0, math.pi/4, math.pi/2, 3 * math.pi/4, math.pi])
print('\nb:')
print(b)
print(torch.sin_(b))
print(b)

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])


In [43]:
a = torch.ones(2,2)
b = torch.rand(2,2)

print('a:')
print(a)
print(a.add(b))
print(a)
print(a.add_(b))
print(a)
print(b)
print(b.mul(b))
print(b)
print(b.mul_(b))
print(b)

a:
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.9247, 1.6166],
        [1.3608, 1.5325]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.9247, 1.6166],
        [1.3608, 1.5325]])
tensor([[1.9247, 1.6166],
        [1.3608, 1.5325]])
tensor([[0.9247, 0.6166],
        [0.3608, 0.5325]])
tensor([[0.8551, 0.3802],
        [0.1302, 0.2835]])
tensor([[0.9247, 0.6166],
        [0.3608, 0.5325]])
tensor([[0.8551, 0.3802],
        [0.1302, 0.2835]])
tensor([[0.8551, 0.3802],
        [0.1302, 0.2835]])


In [47]:
a = torch.rand(2,2)
b = torch.rand(2,2)
c = torch.zeros(2,2)
old_id = id(c)

print(c)
d = torch.matmul(a,b, out = c)
print(c)

assert c is d
assert id(c) == old_id

torch.rand(2,2, out = c)
print(c)
assert id(c) == old_id
print(c)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.1125, 0.1620],
        [0.3376, 0.6033]])
tensor([[0.5125, 0.1549],
        [0.6881, 0.4900]])
tensor([[0.5125, 0.1549],
        [0.6881, 0.4900]])


In [48]:
a = torch.rand(2,2)
b = a
print(a)
print(b)

a[0][1] = 5.7
print(a)
print(b)

tensor([[0.0164, 0.7690],
        [0.7674, 0.4058]])
tensor([[0.0164, 0.7690],
        [0.7674, 0.4058]])
tensor([[0.0164, 5.7000],
        [0.7674, 0.4058]])
tensor([[0.0164, 5.7000],
        [0.7674, 0.4058]])


In [49]:
a = torch.rand(2,2)
b = a.clone()
print(a)
print(b)

a[0][1] = 5.7
print(a)
print(b)

tensor([[0.1548, 0.5201],
        [0.8773, 0.9577]])
tensor([[0.1548, 0.5201],
        [0.8773, 0.9577]])
tensor([[0.1548, 5.7000],
        [0.8773, 0.9577]])
tensor([[0.1548, 0.5201],
        [0.8773, 0.9577]])


In [50]:
if torch.accelerator.is_available():
    print("We have an accelerator")
else:
    print("We dont have an accelerator")

We have an accelerator


In [52]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand((2,2), device = torch.accelerator.current_accelerator())
    print(gpu_rand)
    print(gpu_rand.device)
else:
    print("Sorry cpu only!")

tensor([[0.0669, 0.9448],
        [0.2207, 0.2721]], device='cuda:0')
cuda:0


In [54]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print("Device = {}".format(my_device))

x = torch.rand(2,2, device = my_device)
print(x, x.device)

Device = cuda
tensor([[0.6396, 0.1476],
        [0.8214, 0.4767]], device='cuda:0') cuda:0


In [55]:
a = torch.rand(3, 4, 4)
b = a.unsqueeze(0)

print(a)
print(b)

print(a.shape)
print(b.shape)

tensor([[[0.1226, 0.2742, 0.8893, 0.7444],
         [0.8095, 0.2511, 0.9308, 0.0890],
         [0.4759, 0.5104, 0.5840, 0.1227],
         [0.9587, 0.9914, 0.1547, 0.5185]],

        [[0.2337, 0.9794, 0.7788, 0.7945],
         [0.6613, 0.4502, 0.7815, 0.5085],
         [0.3176, 0.7582, 0.6569, 0.3704],
         [0.3630, 0.0578, 0.3629, 0.2974]],

        [[0.2275, 0.0484, 0.8916, 0.0532],
         [0.9964, 0.2377, 0.4616, 0.9079],
         [0.6650, 0.3573, 0.0975, 0.2956],
         [0.9027, 0.3112, 0.9167, 0.4139]]])
tensor([[[[0.1226, 0.2742, 0.8893, 0.7444],
          [0.8095, 0.2511, 0.9308, 0.0890],
          [0.4759, 0.5104, 0.5840, 0.1227],
          [0.9587, 0.9914, 0.1547, 0.5185]],

         [[0.2337, 0.9794, 0.7788, 0.7945],
          [0.6613, 0.4502, 0.7815, 0.5085],
          [0.3176, 0.7582, 0.6569, 0.3704],
          [0.3630, 0.0578, 0.3629, 0.2974]],

         [[0.2275, 0.0484, 0.8916, 0.0532],
          [0.9964, 0.2377, 0.4616, 0.9079],
          [0.6650, 0.3573, 0.0975,

In [56]:
a = torch.rand(1, 20)
b = a.squeeze(0)

c = a.squeeze(1)

print(a)
print(b)
print(c)

tensor([[0.4362, 0.6996, 0.4265, 0.4958, 0.8463, 0.6671, 0.4801, 0.6904, 0.9355,
         0.6260, 0.3534, 0.6638, 0.4563, 0.1091, 0.3069, 0.7274, 0.5164, 0.6845,
         0.2073, 0.9727]])
tensor([0.4362, 0.6996, 0.4265, 0.4958, 0.8463, 0.6671, 0.4801, 0.6904, 0.9355,
        0.6260, 0.3534, 0.6638, 0.4563, 0.1091, 0.3069, 0.7274, 0.5164, 0.6845,
        0.2073, 0.9727])
tensor([[0.4362, 0.6996, 0.4265, 0.4958, 0.8463, 0.6671, 0.4801, 0.6904, 0.9355,
         0.6260, 0.3534, 0.6638, 0.4563, 0.1091, 0.3069, 0.7274, 0.5164, 0.6845,
         0.2073, 0.9727]])


In [58]:
a = torch.rand(5, 5)
print(a)
a.unsqueeze_(1)
print(a)
print(a.shape)

tensor([[0.6861, 0.4209, 0.8046, 0.2621, 0.0638],
        [0.0036, 0.7032, 0.3051, 0.8070, 0.9271],
        [0.6647, 0.9296, 0.3848, 0.9357, 0.2616],
        [0.4344, 0.8323, 0.2410, 0.8815, 0.6226],
        [0.4902, 0.9279, 0.8751, 0.2943, 0.5485]])
tensor([[[0.6861, 0.4209, 0.8046, 0.2621, 0.0638]],

        [[0.0036, 0.7032, 0.3051, 0.8070, 0.9271]],

        [[0.6647, 0.9296, 0.3848, 0.9357, 0.2616]],

        [[0.4344, 0.8323, 0.2410, 0.8815, 0.6226]],

        [[0.4902, 0.9279, 0.8751, 0.2943, 0.5485]]])
torch.Size([5, 1, 5])


In [65]:
a = torch.rand(6, 10, 10)
b = a.reshape(6*5, 20)
print(a.shape)
print(b.shape)



torch.Size([6, 10, 10])
torch.Size([30, 20])


In [66]:
print(a)

tensor([[[0.3389, 0.1570, 0.8510, 0.2368, 0.5856, 0.0473, 0.3832, 0.5937,
          0.0432, 0.5086],
         [0.6436, 0.2929, 0.4430, 0.6047, 0.3560, 0.0708, 0.0165, 0.7588,
          0.8113, 0.7934],
         [0.5494, 0.7923, 0.0504, 0.2423, 0.0994, 0.7333, 0.2133, 0.4804,
          0.6784, 0.7660],
         [0.9398, 0.4755, 0.8390, 0.1105, 0.6530, 0.1486, 0.7463, 0.4862,
          0.8900, 0.2333],
         [0.1601, 0.9848, 0.3148, 0.3778, 0.9643, 0.7167, 0.2885, 0.2947,
          0.6685, 0.2444],
         [0.1097, 0.5211, 0.2914, 0.1477, 0.7682, 0.3546, 0.9673, 0.5902,
          0.6875, 0.2155],
         [0.3641, 0.8346, 0.8184, 0.3437, 0.0407, 0.7908, 0.7235, 0.9924,
          0.9856, 0.5153],
         [0.6064, 0.7479, 0.7524, 0.4061, 0.8811, 0.0725, 0.2952, 0.1566,
          0.0744, 0.3726],
         [0.0156, 0.2171, 0.6828, 0.9717, 0.6002, 0.0831, 0.7908, 0.9766,
          0.6423, 0.1724],
         [0.2907, 0.8025, 0.4070, 0.5737, 0.9400, 0.2652, 0.4402, 0.8561,
          0.3537,

In [67]:
print(b)

tensor([[0.3389, 0.1570, 0.8510, 0.2368, 0.5856, 0.0473, 0.3832, 0.5937, 0.0432,
         0.5086, 0.6436, 0.2929, 0.4430, 0.6047, 0.3560, 0.0708, 0.0165, 0.7588,
         0.8113, 0.7934],
        [0.5494, 0.7923, 0.0504, 0.2423, 0.0994, 0.7333, 0.2133, 0.4804, 0.6784,
         0.7660, 0.9398, 0.4755, 0.8390, 0.1105, 0.6530, 0.1486, 0.7463, 0.4862,
         0.8900, 0.2333],
        [0.1601, 0.9848, 0.3148, 0.3778, 0.9643, 0.7167, 0.2885, 0.2947, 0.6685,
         0.2444, 0.1097, 0.5211, 0.2914, 0.1477, 0.7682, 0.3546, 0.9673, 0.5902,
         0.6875, 0.2155],
        [0.3641, 0.8346, 0.8184, 0.3437, 0.0407, 0.7908, 0.7235, 0.9924, 0.9856,
         0.5153, 0.6064, 0.7479, 0.7524, 0.4061, 0.8811, 0.0725, 0.2952, 0.1566,
         0.0744, 0.3726],
        [0.0156, 0.2171, 0.6828, 0.9717, 0.6002, 0.0831, 0.7908, 0.9766, 0.6423,
         0.1724, 0.2907, 0.8025, 0.4070, 0.5737, 0.9400, 0.2652, 0.4402, 0.8561,
         0.3537, 0.7494],
        [0.4135, 0.6309, 0.2467, 0.1136, 0.0674, 0.6548, 0.6

In [72]:
a = torch.rand(3, 6, 3)
b = a.reshape(9, 6).clone()

In [73]:
print(a)


tensor([[[2.2977e-01, 6.7164e-01, 2.5264e-01],
         [8.6508e-01, 3.0319e-01, 8.5645e-02],
         [1.3237e-01, 2.3664e-02, 2.1812e-01],
         [7.2075e-01, 1.8426e-01, 2.2073e-01],
         [9.4742e-01, 2.4552e-01, 5.3212e-01],
         [6.8633e-01, 6.6569e-01, 3.3063e-01]],

        [[6.6452e-01, 4.5092e-01, 7.5951e-01],
         [1.8454e-01, 6.4803e-01, 5.4997e-01],
         [1.3603e-01, 3.9959e-01, 7.1770e-01],
         [2.0949e-01, 2.2955e-02, 7.5261e-01],
         [3.9063e-01, 7.0912e-01, 8.0113e-03],
         [2.8419e-04, 4.4554e-02, 4.4758e-01]],

        [[9.5328e-01, 9.0328e-01, 3.4423e-01],
         [2.7148e-01, 5.6791e-01, 8.6083e-01],
         [9.7153e-01, 8.3541e-02, 8.6269e-01],
         [1.4060e-01, 2.8055e-01, 3.3985e-02],
         [3.0889e-01, 4.0136e-01, 4.6024e-02],
         [7.5747e-01, 8.6258e-01, 1.5855e-01]]])


In [74]:
print(b)

tensor([[2.2977e-01, 6.7164e-01, 2.5264e-01, 8.6508e-01, 3.0319e-01, 8.5645e-02],
        [1.3237e-01, 2.3664e-02, 2.1812e-01, 7.2075e-01, 1.8426e-01, 2.2073e-01],
        [9.4742e-01, 2.4552e-01, 5.3212e-01, 6.8633e-01, 6.6569e-01, 3.3063e-01],
        [6.6452e-01, 4.5092e-01, 7.5951e-01, 1.8454e-01, 6.4803e-01, 5.4997e-01],
        [1.3603e-01, 3.9959e-01, 7.1770e-01, 2.0949e-01, 2.2955e-02, 7.5261e-01],
        [3.9063e-01, 7.0912e-01, 8.0113e-03, 2.8419e-04, 4.4554e-02, 4.4758e-01],
        [9.5328e-01, 9.0328e-01, 3.4423e-01, 2.7148e-01, 5.6791e-01, 8.6083e-01],
        [9.7153e-01, 8.3541e-02, 8.6269e-01, 1.4060e-01, 2.8055e-01, 3.3985e-02],
        [3.0889e-01, 4.0136e-01, 4.6024e-02, 7.5747e-01, 8.6258e-01, 1.5855e-01]])


In [75]:
a[0][0][0] = 1
print(b)

tensor([[2.2977e-01, 6.7164e-01, 2.5264e-01, 8.6508e-01, 3.0319e-01, 8.5645e-02],
        [1.3237e-01, 2.3664e-02, 2.1812e-01, 7.2075e-01, 1.8426e-01, 2.2073e-01],
        [9.4742e-01, 2.4552e-01, 5.3212e-01, 6.8633e-01, 6.6569e-01, 3.3063e-01],
        [6.6452e-01, 4.5092e-01, 7.5951e-01, 1.8454e-01, 6.4803e-01, 5.4997e-01],
        [1.3603e-01, 3.9959e-01, 7.1770e-01, 2.0949e-01, 2.2955e-02, 7.5261e-01],
        [3.9063e-01, 7.0912e-01, 8.0113e-03, 2.8419e-04, 4.4554e-02, 4.4758e-01],
        [9.5328e-01, 9.0328e-01, 3.4423e-01, 2.7148e-01, 5.6791e-01, 8.6083e-01],
        [9.7153e-01, 8.3541e-02, 8.6269e-01, 1.4060e-01, 2.8055e-01, 3.3985e-02],
        [3.0889e-01, 4.0136e-01, 4.6024e-02, 7.5747e-01, 8.6258e-01, 1.5855e-01]])


In [12]:
torch.manual_seed(42)

In [ ]:
a = torch.rand(4,2,3)
print(a)

tensor([[[0.1390, 0.3954, 0.4336],
         [0.7955, 0.4499, 0.5814]],

        [[0.7073, 0.0716, 0.3353],
         [0.0488, 0.1794, 0.3165]],

        [[0.3448, 0.3996, 0.4245],
         [0.6298, 0.6041, 0.9399]],

        [[0.6663, 0.2567, 0.1356],
         [0.2332, 0.0892, 0.3827]]])


In [6]:
b = torch.rand(2,3)
print(b)

tensor([[0.4145, 0.5043, 0.2289],
        [0.0434, 0.1198, 0.5477]])


In [13]:
a = torch.rand(4,2,3)
print(a)

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]],

        [[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317]]])


In [17]:
c = a @ torch.transpose(b, -1, -2)

In [18]:
print(b)
print(torch.transpose(b, -1, -2))

tensor([[0.4145, 0.5043, 0.2289],
        [0.0434, 0.1198, 0.5477]])
tensor([[0.4145, 0.0434],
        [0.5043, 0.1198],
        [0.2289, 0.5477]])


In [19]:
print(c.shape)

torch.Size([4, 2, 2])


In [20]:
d = torch.transpose(b, -1, -2) @ a

In [21]:
print(d.shape)

torch.Size([4, 3, 3])


In [22]:
m = d.view(2, 2, 3, 3)

In [23]:
print(d)
print(m)

tensor([[[0.4072, 0.3962, 0.1847],
         [0.5598, 0.5082, 0.2651],
         [0.7274, 0.4233, 0.4168]],

        [[0.1121, 0.3694, 0.4156],
         [0.1453, 0.5122, 0.5455],
         [0.1317, 0.6936, 0.5404]],

        [[0.3789, 0.2737, 0.3320],
         [0.4898, 0.3924, 0.4425],
         [0.4342, 0.6149, 0.4840]],

        [[0.1296, 0.2729, 0.1478],
         [0.1873, 0.3520, 0.2356],
         [0.3028, 0.3062, 0.5173]]])
tensor([[[[0.4072, 0.3962, 0.1847],
          [0.5598, 0.5082, 0.2651],
          [0.7274, 0.4233, 0.4168]],

         [[0.1121, 0.3694, 0.4156],
          [0.1453, 0.5122, 0.5455],
          [0.1317, 0.6936, 0.5404]]],


        [[[0.3789, 0.2737, 0.3320],
          [0.4898, 0.3924, 0.4425],
          [0.4342, 0.6149, 0.4840]],

         [[0.1296, 0.2729, 0.1478],
          [0.1873, 0.3520, 0.2356],
          [0.3028, 0.3062, 0.5173]]]])


In [25]:
new_mat = m[:, :, :1, :]
print(new_mat, new_mat.shape)

tensor([[[[0.4072, 0.3962, 0.1847]],

         [[0.1121, 0.3694, 0.4156]]],


        [[[0.3789, 0.2737, 0.3320]],

         [[0.1296, 0.2729, 0.1478]]]]) torch.Size([2, 2, 1, 3])


In [37]:
random_mat = torch.rand(1, 4, 10)
print(random_mat.shape)
print(random_mat)

torch.Size([1, 4, 10])
tensor([[[0.3962, 0.6611, 0.6343, 0.5057, 0.5450, 0.8900, 0.9441, 0.2785,
          0.1595, 0.0827],
         [0.1342, 0.5358, 0.3882, 0.0842, 0.8738, 0.1011, 0.5189, 0.2637,
          0.1016, 0.5497],
         [0.0394, 0.5457, 0.0690, 0.3388, 0.5169, 0.1234, 0.6189, 0.3711,
          0.3066, 0.9990],
         [0.8888, 0.0974, 0.2071, 0.0268, 0.3933, 0.0478, 0.4825, 0.2491,
          0.2336, 0.3777]]])


In [38]:
num_tokens = random_mat.shape[1]
random_mat = random_mat[:, max(-5, -1 * num_tokens):, :]
print(random_mat.shape)
print(random_mat)

torch.Size([1, 4, 10])
tensor([[[0.3962, 0.6611, 0.6343, 0.5057, 0.5450, 0.8900, 0.9441, 0.2785,
          0.1595, 0.0827],
         [0.1342, 0.5358, 0.3882, 0.0842, 0.8738, 0.1011, 0.5189, 0.2637,
          0.1016, 0.5497],
         [0.0394, 0.5457, 0.0690, 0.3388, 0.5169, 0.1234, 0.6189, 0.3711,
          0.3066, 0.9990],
         [0.8888, 0.0974, 0.2071, 0.0268, 0.3933, 0.0478, 0.4825, 0.2491,
          0.2336, 0.3777]]])


In [39]:
new_rand = torch.rand(1, 1, 10)
print(new_rand.shape)
soln = torch.cat((random_mat, new_rand), dim = 1)

torch.Size([1, 1, 10])


In [40]:
print(soln.shape)

torch.Size([1, 5, 10])


In [41]:
print(soln)

tensor([[[0.3962, 0.6611, 0.6343, 0.5057, 0.5450, 0.8900, 0.9441, 0.2785,
          0.1595, 0.0827],
         [0.1342, 0.5358, 0.3882, 0.0842, 0.8738, 0.1011, 0.5189, 0.2637,
          0.1016, 0.5497],
         [0.0394, 0.5457, 0.0690, 0.3388, 0.5169, 0.1234, 0.6189, 0.3711,
          0.3066, 0.9990],
         [0.8888, 0.0974, 0.2071, 0.0268, 0.3933, 0.0478, 0.4825, 0.2491,
          0.2336, 0.3777],
         [0.4206, 0.5119, 0.7682, 0.1851, 0.7631, 0.2642, 0.8059, 0.2885,
          0.7350, 0.7467]]])


In [43]:
num_tokens = soln.shape[1]
random_mat = soln[:, max(-4, -1 * num_tokens):, :]
print(random_mat.shape)
print(random_mat)

torch.Size([1, 4, 10])
tensor([[[0.1342, 0.5358, 0.3882, 0.0842, 0.8738, 0.1011, 0.5189, 0.2637,
          0.1016, 0.5497],
         [0.0394, 0.5457, 0.0690, 0.3388, 0.5169, 0.1234, 0.6189, 0.3711,
          0.3066, 0.9990],
         [0.8888, 0.0974, 0.2071, 0.0268, 0.3933, 0.0478, 0.4825, 0.2491,
          0.2336, 0.3777],
         [0.4206, 0.5119, 0.7682, 0.1851, 0.7631, 0.2642, 0.8059, 0.2885,
          0.7350, 0.7467]]])


In [44]:
new_rand = torch.rand(1, 1, 10)
print(new_rand.shape)
soln = torch.cat((random_mat, new_rand), dim = 1)
print(soln)

torch.Size([1, 1, 10])
tensor([[[0.1342, 0.5358, 0.3882, 0.0842, 0.8738, 0.1011, 0.5189, 0.2637,
          0.1016, 0.5497],
         [0.0394, 0.5457, 0.0690, 0.3388, 0.5169, 0.1234, 0.6189, 0.3711,
          0.3066, 0.9990],
         [0.8888, 0.0974, 0.2071, 0.0268, 0.3933, 0.0478, 0.4825, 0.2491,
          0.2336, 0.3777],
         [0.4206, 0.5119, 0.7682, 0.1851, 0.7631, 0.2642, 0.8059, 0.2885,
          0.7350, 0.7467],
         [0.9547, 0.2573, 0.3852, 0.6992, 0.8822, 0.9716, 0.9240, 0.9279,
          0.4288, 0.9079]]])


In [1]:
h = [1,2,3] 
print(h[-1:])

[3]
